apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhcmFzaGdoIiwicGFzc3dvcmQiOiJhcmFzaDI0Z2giLCJlbWFpbCI6Imdob2xhbWRva2h0LmFyYXNoQGdtYWlsLmNvbSIsImF1dGgiOiJZWEpoYzJobmFEcGhjbUZ6YURJMFoyZz0ifX19
kind: Secret
metadata:
  name: regsecret
  namespace: default
type: kubernetes.io/dockerconfigjson
